src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



#[UniqueEntity('Nom')]
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 1,
        max: 255,
        minMessage: 'The title must be at least {{ limit }} characters long',
        maxMessage: 'The title cannot be longer than {{ limit }} characters',
    )]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $Prix = null;

    #[ORM\Column]
    private ?int $Stock = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Photo = null;

    /**
     * @var Collection<int, ContenuPanier>
     */
    #[ORM\OneToMany(targetEntity: ContenuPanier::class, mappedBy: 'produit')]
    private Collection $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->Stock;
    }

    public function setStock(int $Stock): static
    {
        $this->Stock = $Stock;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): static
    {
        $this->Photo = $Photo;

        return $this;
    }

    /**
     * @return Collection<int, ContenuPanier>
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): static
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers->add($contenuPanier);
            $contenuPanier->setProduit($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): static
    {
        if ($this->contenuPaniers->removeElement($contenuPanier)) {
            // set the owning side to null (unless already changed)
            if ($contenuPanier->getProduit() === $this) {
                $contenuPanier->setProduit(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    /**
     * @var Collection<int, Panier>
     */
    #[ORM\OneToMany(targetEntity: Panier::class, mappedBy: 'user')]
    private Collection $paniers;

    #[ORM\Column]
    private ?\DateTime $createdAt = null;

    public function __construct()
    {
        $this->paniers = new ArrayCollection();
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): static
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->setUser($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): static
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getUser() === $this) {
                $panier->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

}

src/Controller/SuperAdminController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use App\Entity\Panier;
use App\Entity\ContenuPanier;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\User;
use DateTime;
use Symfony\Contracts\Translation\TranslatorInterface;

#[IsGranted('ROLE_SUPER_ADMIN')]
class SuperAdminController extends AbstractController
{
    #[Route('/super/admin', name: 'app_super_admin')]
    public function index(EntityManagerInterface $em): Response
    {
        // Récupère tous les paniers non achetés
        $paniers = $em->getRepository(Panier::class)->findBy(['etat' => false]);

        // Prépare les données des paniers pour l'affichage
        $allPanierNotPurchased = [];
        foreach ($paniers as $panier) {
            $allPanierNotPurchased[] = [
                'panier_id' => $panier->getId(),
                'user_email' => $panier->getUser()->getEmail(),
            ];
        }

        // Détermine les dates de début et de fin de la journée actuelle
        $dayStart = new DateTime('today');
        $dayEnd = new DateTime('tomorrow');

        // Récupère les utilisateurs inscrits aujourd'hui
        $users = $em->getRepository(User::class)->createQueryBuilder('u')
            ->where('u.createdAt BETWEEN :dayStart AND :dayEnd')
            ->setParameter('dayStart', $dayStart)
            ->setParameter('dayEnd', $dayEnd)
            ->orderBy('u.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
        
        return $this->render('super_admin/index.html.twig', [
            'paniers' => $allPanierNotPurchased,
            'users' => $users
        ]);
    }

    #[Route('/super/admin/showCartByID/{id}', name: 'app_super_admin_cart_by_id')]
    public function showCartByID(EntityManagerInterface $em, int $id): Response
    {
        // Récupère le panier avec l'ID donné et l'état "0" (non acheté)
        $panier = $em->getRepository(Panier::class)->findOneBy([
            'id' => $id,
            'etat' => "0"
        ]);

        // Si le panier n'existe pas, lance une exception
        if (!$panier) {
            throw $this->createNotFoundException('No cart found for id ' . $id);
        }
        
        // Récupère l'utilisateur associé au panier
        $user = $panier->getUser();
        // Récupère les contenus du panier
        $contenuPanier = $em->getRepository(ContenuPanier::class)->findBy(['panier' => $panier]);

        return $this->render('super_admin/contenuUserPanier.html.twig', [
            'user' => $user,
            'panier' => $panier,
            'contenuPanier' => $contenuPanier,
        ]);
    }
}

templates/super_admin/contenuUserPanier.html.twig
{% extends 'base.html.twig' %}

{% block title %}ColMarket
{% endblock %}

{% block body %}
{{ include('header.html.twig') }}
<main>
	<h1 class="text-2xl mb-6">{{ 'Mpanier.contenu'|trans }} #{{ panier.id }} {{ 'SuperAdmin.appartenant'|trans }} <strong>{{user.email}}</strong></h1>

	<h2 class="text-xl mb-4">{{ 'profil.dateAchat'|trans }} :
		{{ panier.dateAchat ? panier.dateAchat|date('d/m/Y H:i') : 'N/A' }}
	</h2>

	<table class="min-w-full bg-white border border-gray-200">
        <thead>
            <tr class="bg-gray-100 border-b">
                <th class="px-4 py-2 text-left text-gray-600">{{ 'Mproduits.titre'|trans }}</th>
                <th class="px-4 py-2 text-left text-gray-600">{{ 'Mpanier.quantite'|trans }}</th>
                <th class="px-4 py-2 text-left text-gray-600">{{ 'Mpanier.prixu'|trans }}</th>
                <th class="px-4 py-2 text-left text-gray-600">Total</th>
            </tr>
        </thead>
        <tbody>
            {% set totalGeneral = 0 %}
            {% for contenu in contenuPanier %}
                <tr class="border-b hover:bg-gray-50">
                    <td class="px-4 py-2">{{ contenu.produit.nom }}</td>
                    <td class="px-4 py-2">{{ contenu.quantite }}</td>
                    <td class="px-4 py-2">{{ contenu.produit.prix }} €</td>
                    <td class="px-4 py-2">{{ contenu.produit.prix * contenu.quantite }} €</td>
                </tr>
                {% set totalGeneral = totalGeneral + (contenu.produit.prix * contenu.quantite) %}
            {% endfor %}
            <tr class="bg-gray-100">
					<td colspan="3" class="px-4 py-2 text-center">
						<strong>Total : {{ totalGeneral }}€</strong>
					</td>
				</tr>
        </tbody>
    </table>
</main>
{% endblock %}

templates/super_admin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SuperAdminController!
{% endblock %}

{% block body %}
	{{ include('header.html.twig') }}
	<main>
		<h1 class="text-2xl font-bold mb-6 mx-4">{{ 'SuperAdmin.listePanier'|trans }}</h1>

		<table class="min-w-full bg-white border border-gray-200 mb-8">
            <thead>
                <tr class="bg-gray-100 border-b">
                    <th class="px-4 py-2 text-left text-gray-600">{{ 'SuperAdmin.numPanier'|trans }}</th>
                    <th class="px-4 py-2 text-left text-gray-600">{{ 'SuperAdmin.utilisateur'|trans }}</th>
                    <th class="px-4 py-2 text-left text-gray-600">{{ 'SuperAdmin.contenu'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for panier in paniers %}
                    <tr class="border-b hover:bg-gray-50">
                        <td class="px-4 py-2">{{ panier.panier_id }}</td>
                        <td class="px-4 py-2">{{ panier.user_email }}</td>
                        <td class="px-4 py-2">
                            <a href="{{ path('app_super_admin_cart_by_id', {id: panier.panier_id} )}}" class="text-blue-500 hover:underline">{{ 'SuperAdmin.contenu'|trans }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2 class="text-xl font-bold mb-4 mx-4">{{ 'SuperAdmin.inscription'|trans }} :</h2>

        {% if users is empty %}
            <p>Aucun utilisateur ne s'est inscrit aujourd'hui.</p>
        {% else %}
            <table class="min-w-full bg-white border border-gray-200">
                <thead>
                    <tr class="bg-gray-100 border-b">
                        <th class="px-4 py-2 text-left text-gray-600">ID</th>
                        <th class="px-4 py-2 text-left text-gray-600">Email</th>
                        <th class="px-4 py-2 text-left text-gray-600">{{ 'SuperAdmin.dateInscription'|trans }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr class="border-b hover:bg-gray-50">
                            <td class="px-4 py-2">{{ user.id }}</td>
                            <td class="px-4 py-2">{{ user.email }}</td>
                            <td class="px-4 py-2">{{ user.createdAt ? user.createdAt|date('d/m/Y H:i') : 'N/A' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
	</main>
{% endblock %}